import pandas as pd
import os

# Centralized directory paths
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
REPORTS_DIR = os.path.join(PROJECT_ROOT, "Reports")

# ## symbols to analyze  #### Keep for future reference
# stock_symbols = ['A', 'AAPL', 'ADBE', 'AMD', 'AMZN', 'ANET', 
# 'APP', 'AVGO', 'BIIB', 'CAT', 
# 'COIN', 'CRM', 'CRWV', 'CVLT', 'DASH',
# 'FFIV', 'FTNT', 'GOOGL',
# 'HIMS', 'HOOD', 'HUBS', 'INTU', 'IT',
# 'LYV', 'MCK', 'META', 'MRK', 'MRVL', 'MU',
# 'NOW', 'NVDA', 'OKTA', 'ORCL', 'PANW', 'REGN', 'RSG', 'RTX', 'SNOW',
# 'SOFI', 'SOUN', 'TEAM', 'TSLA', 'TTD', 'UI', 'UNH', 'UPST', 'URI', 'VRT', 
# 'SHOP'] 

## symbols to analyze
stock_symbols = ['AAPL', 'ADSK', 'ADBE', 'AMD', 'AMZN', 'ANET', 'APH', 'APP', 'ARM', 'AVAV',
'ASML', 'AVGO', 'AXON', 'BAC', 'BIIB', 'BLK', 'CDNS', 'CDW', 'COF', 'COIN', 'CRWD', 'CRM',
'CRWV', 'CVLT', 'DASH', 'DDOG', 'ENPH',
'FLEX', 'FTNT', 'GLW', 'GOOGL', 'GTLB', 'HIMS', 'HOOD', 'HUBS', 'INTC', 'INTU', 'IONQ',
'IREN', 'IT', 'JOBY', 'KLAC', 'KVYO', 'LRCX', 'MCK', 'MRK', 'META', 'MRVL',
'MSFT', 'MU', 'NBIS', 'NET', 'NFLX', 'NOW', 'NSC', 'NVDA', 'ORCL', 'PANW', 'PAYX', 'PCTY', 
'PLTR', 'POOL', 'PWR', 'RCL','REGN', 'RTX',
'SHOP', 'SNOW', 'SOFI', 'SOUN', 'TEAM', 'TEM', 'TMO', 'TMUS', 'TSLA', 'TTD', 'TYL', 'TWLO', 'UBER',
'UI', 'UNH', 'UPST', 'VEEV', 'VRT', 'WDAY', 'ZS']

symbol_sector = {
    'AAPL': 'Technology',
    'AVAV': 'Technology',
    'ADSK': 'Technology',
    'ADBE': 'Technology',
    'AMD': 'Technology',
    'AMZN': 'Consumer Discretionary',
    'ANET': 'Technology',
    'APH': 'Industrials',
    'APP': 'Communication Services',
    'ARM': 'Technology',
    'ASML': 'Technology',
    'AVGO': 'Technology',
    'AXON': 'Industrials',
    'BAC': 'Financials',
    'BIIB': 'Health Care',
    'BLK': 'Financials',
    'CDNS': 'Technology',
    'CDW': 'Technology',
    'COF': 'Financials',
    'COIN': 'Financials',
    'CRWD': 'Technology',
    'CRM': 'Technology',
    'CRWV': 'Technology',
    'CVLT': 'Technology',
    'DASH': 'Communication Services',
    'DDOG': 'Technology',
    'ELV': 'Health Care',
    'ENPH': 'Technology',
    'FANG': 'Energy',
    'FLEX': 'Industrials',
    'FTNT': 'Technology',
    'GLW': 'Materials',
    'GOOGL': 'Communication Services',
    'GTLB': 'Technology',
    'HIMS': 'Health Care',
    'HOOD': 'Financials',
    'HUBS': 'Technology',
    'INTC': 'Technology',
    'INTU': 'Technology',
    'IONQ': 'Technology',
    'IREN': 'Energy',
    'IT': 'Technology',
    'JOBY': 'Industrials',
    'KLAC': 'Technology',
    'KVYO': 'Technology',
    'LLY': 'Health Care',
    'LRCX': 'Technology',
    'MCK': 'Health Care',
    'MRK': 'Health Care',
    'META': 'Communication Services',
    'MPWR': 'Technology',
    'MRVL': 'Technology',
    'MSFT': 'Technology',
    'MU': 'Technology',
    'NBIS': 'Technology',
    'NET': 'Technology',
    'NFLX': 'Communication Services',
    'NOW': 'Technology',
    'NSC': 'Industrials',
    'NVDA': 'Technology',
    'ORCL': 'Technology',
    'PANW': 'Technology',
    'PATH': 'Technology',
    'PAYX': 'Industrials',
    'PCTY': 'Technology',
    'PLTR': 'Technology',
    'POOL': 'Consumer Discretionary',
    'PWR': 'Industrials',
    'RCL': 'Consumer Discretionary',
    'REGN': 'Health Care',
    'RTX': 'Industrials',
    'SHOP': 'Technology',
    'SNOW': 'Technology',
    'SOFI': 'Financials',
    'SOUN': 'Technology',
    'TEAM': 'Technology',
    'TEM': 'Health Care',
    'TMO': 'Health Care',
    'TMUS': 'Communication Services',
    'TSLA': 'Consumer Discretionary',
    'TTD': 'Communication Services',
    'TXN': 'Technology',
    'TYL': 'Technology',
    'TWLO': 'Technology',
    'UBER': 'Consumer Discretionary',
    'UI': 'Technology',
    'UNH': 'Health Care',
    'UPST': 'Financials',
    'VEEV': 'Technology',
    'VRT': 'Industrials',
    'WAT': 'Health Care',
    'WDAY': 'Technology',
    'ZS': 'Technology'
}


symbol_name = {
    'AAPL': 'Apple Inc.',
    'ADSK': 'Autodesk, Inc.',
    'ADBE': 'Adobe Inc.',
    'AMD': 'Advanced Micro Devices, Inc.',
    'AMZN': 'Amazon.com, Inc.',
    'ANET': 'Arista Networks, Inc.',
    'APH': 'Amphenol Corporation',
    'APP': 'AppLovin Corporation',
    'ARM': 'Arm Holdings plc',
    'ASML': 'ASML Holding N.V.',
    'AVAV': 'AeroVironment, Inc.',
    'AVGO': 'Broadcom Inc.',
    'AXON': 'Axon Enterprise, Inc.',
    'BAC': 'Bank of America Corporation',
    'BIIB': 'Biogen Inc.',
    'BLK': 'BlackRock, Inc.',
    'CDNS': 'Cadence Design Systems, Inc.',
    'CDW': 'CDW Corporation',
    'COF': 'Capital One Financial Corporation',
    'COIN': 'Coinbase Global, Inc.',
    'CRWD': 'CrowdStrike Holdings, Inc.',
    'CRM': 'Salesforce, Inc.',
    'CRWV': 'CoreWeave, Inc.',
    'CVLT': 'Commvault Systems, Inc.',
    'DASH': 'DoorDash, Inc.',
    'DDOG': 'Datadog, Inc.',
    'ELV': 'Elevance Health, Inc.',
    'ENPH': 'Enphase Energy, Inc.',
    'FANG': 'Diamondback Energy, Inc.',
    'FLEX': 'Flex Ltd.',
    'FTNT': 'Fortinet, Inc.',
    'GLW': 'Corning Incorporated',
    'GOOGL': 'Alphabet Inc.',
    'GTLB': 'GitLab Inc.',
    'HIMS': 'Hims & Hers Health, Inc.',
    'HOOD': 'Robinhood Markets, Inc.',
    'HUBS': 'HubSpot, Inc.',
    'INTC': 'Intel Corporation',
    'INTU': 'Intuit Inc.',
    'IONQ': 'IonQ, Inc.',
    'IREN': 'Iris Energy Limited',
    'ISRG': 'Intuitive Surgical, Inc.',
    'IT': 'Gartner, Inc.',
    'JOBY': 'Joby Aviation, Inc.',
    'KLAC': 'KLA Corporation',
    'KVYO': 'Klaviyo, Inc.',
    'LLY': 'Eli Lilly and Company',
    'LRCX': 'Lam Research Corporation',
    'MCK': 'McKesson Corporation',
    'MRK': 'Merck & Co., Inc.',
    'META': 'Meta Platforms, Inc.',
    'MPWR': 'Monolithic Power Systems, Inc.',
    'MRVL': 'Marvell Technology, Inc.',
    'MSFT': 'Microsoft Corporation',
    'MU': 'Micron Technology, Inc.',
    'NBIS': 'Nebius Group',
    'NET': 'Cloudflare, Inc.',
    'NFLX': 'Netflix, Inc.',
    'NOW': 'ServiceNow, Inc.',
    'NSC': 'Norfolk Southern Corporation',
    'NVDA': 'NVIDIA Corporation',
    'ORCL': 'Oracle Corporation',
    'PANW': 'Palo Alto Networks, Inc.',
    'PAYX': 'Paychex, Inc.',
    'PATH': 'UiPath, Inc.',
    'PCTY': 'Paylocity Holding Corporation',
    'PLTR': 'Palantir Technologies Inc.',
    'POOL': 'Pool Corporation',
    'PWR': 'Quanta Services, Inc.',
    'RCL': 'Royal Caribbean Cruises Ltd.',
    'REGN': 'Regeneron Pharmaceuticals, Inc.',
    'RTX': 'RTX Corporation',
    'SHOP': 'Shopify Inc.',
    'SNOW': 'Snowflake Inc.',
    'SOFI': 'SoFi Technologies, Inc.',
    'SOUN': 'SoundHound AI, Inc.',
    'TEAM': 'Atlassian Corporation',
    'TEM': 'Tempus AI, Inc.',
    'TMO': 'Thermo Fisher Scientific Inc.',
    'TMUS': 'T-Mobile US, Inc.',
    'TSLA': 'Tesla, Inc.',
    'TTD': 'The Trade Desk, Inc.',
    'TXN': 'Texas Instruments Incorporated',
    'TYL': 'Tyler Technologies, Inc.',
    'TWLO': 'Twilio Inc.',
    'UBER': 'Uber Technologies, Inc.',
    'UI': 'Ubiquiti Inc.',
    'UNH': 'UnitedHealth Group Incorporated',
    'UPST': 'Upstart Holdings, Inc.',
    'VEEV': 'Veeva Systems Inc.',
    'VRT': 'Vertiv Holdings Co',
    'WAT': 'Waters Corporation',
    'WDAY': 'Workday, Inc.',
    'ZS': 'Zscaler, Inc.'
}


# Create stock_sector_df from stock_symbols list to ensure exact match
stock_sector_df = pd.DataFrame(stock_symbols, columns=['Symbol'])

# Add Sector and Company Name columns
stock_sector_df["Sector"] = stock_sector_df["Symbol"].map(symbol_sector)
stock_sector_df["Company Name"] = stock_sector_df["Symbol"].map(symbol_name)

# sector_map = {
#     "Consumer Cyclical": "Consumer Discretionary",
#     "Consumer Defensive": "Consumer Staples",
#     "Information Technology": "Technology",
#     "Healthcare": "Health Care"
# }

# stock_sector_df["Sector"] = stock_sector_df["Sector"].replace(sector_map)

if __name__ == "__main__":
    print(stock_sector_df)